---

- name: "Swarm::Server | Check required variables"
  ansible.builtin.fail: msg="Variable '{{ item }}' is not defined"
  when: (vars[item] is not defined) or (vars[item] is none) or (vars[item]|length == 0)
  with_items: "{{ required_vars }}"

# Setup Docker daemon

- name: "Swarm::Server | mkdir /etc/systemd/system/docker.service.d/"
  file:
    path: /etc/systemd/system/docker.service.d/
    state: directory

- name: "Swarm::Server | Copy /etc/systemd/system/docker.service.d/docker.conf"
  template:
    src: docker.conf.j2
    dest: /etc/systemd/system/docker.service.d/docker.conf
    mode: 0440

# Update /etc/docker/daemon.json

- name: Load current facts
  slurp:
    path: "/etc/docker/daemon.json"
  register: daemon_json_raw

- name: Enable fact
  set_fact:
    daemon_json: "{{ daemon_json | combine({ 
      'tlsverify': true,
      'tlscacert': '/etc/docker/ca.pem',
      'tlscert': '/etc/docker/server-cert.pem',
      'tlskey': '/etc/docker/server-key.pem',
      'hosts': [ 
        'tcp://127.0.0.1:2376', 
        'tcp://' + swarm_server_node_ip + ':2376', 
        'unix:///var/run/docker.sock' 
      ] 
    }) }}"
  vars:
    daemon_json: "{{ daemon_json_raw.content | b64decode }}"

- name: write modified data to file
  copy:
    content: "{{ daemon_json | to_nice_json }}"
    dest: /etc/docker/daemon.json

# Copy CA certs

- name: "Swarm::Server | Copy /etc/docker/ca.pem"
  copy:
    src: "{{ swarm_server_ca_folder }}/{{ swarm_server_ca_domain }}.crt.pem"
    dest: /etc/docker/ca.pem
    owner: root
    group: docker
    mode: '0440'

# Copy Server certs

- name: "Swarm::Server | Copy /etc/docker/server-cert.pem"
  copy:
    src: "{{ swarm_server_ca_folder }}/servers/{{ swarm_server_hostname }}.{{ swarm_server_ca_domain }}.crt.pem"
    dest: /etc/docker/server-cert.pem
    owner: root
    group: docker
    mode: '0440'

- name: "Swarm::Server | Copy /etc/docker/server-key.pem"
  copy:
    src: "{{ swarm_server_ca_folder }}/servers/{{ swarm_server_hostname }}.{{ swarm_server_ca_domain }}.key.pem"
    dest: /etc/docker/server-key.pem
    owner: root
    group: docker
    mode: '0440'

- name: "Swarm::Server | Restart docker service"
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: docker